### ISSUE TITLE
Lỗi bảo mật: Ai cũng có thể chỉnh sửa lại thông tin sổ tiết kiệm của mình

### ISSUE THREAD

**Issue by leminhthanh1998** [leminhthanh1998/MoneyLover#13]
Tất cả các tài khoản khi đăng nhập vào đều hiển thị chung thông tin về các sổ tiết kiệm và đều có thể chỉnh sửa chúng. Điều này cực kì không an toàn!

**Comment by nnb963** [comment]
Chức năng này không được mô tả trong tài liệu. ok?
